test_user_lock finish
CoLearn-Dev/colink-sdk-rust-dev pull request #46
Opened 2023-01-30 07:46 UTC by walotta

The transformation from sample to test of user_lock is complete

2023-01-30 10:48 UTC, stneng requested changes
Thanks for the update, please see the detailed comments.

2023-01-30 10:48 UTC, stneng commented on tests/test_user_lock.rs
> +    let cl = CoLink::new(&core_addr, &user_jwt);
-> `let cl = is.get_colink().switch_to_generated_user().await?;`

2023-01-30 10:48 UTC, stneng commented on tests/test_user_remote_storage.rs
> +    let user_b_jwt = gen_new_uesr(&cl).await?;
please use two servers.
```
let isa = InstantServer::new();
let isb = InstantServer::new();
let cla = isa.get_colink().switch_to_generated_user().await?;
let clb = isb.get_colink().switch_to_generated_user().await?;
```

2023-01-30 10:48 UTC, stneng commented on tests/test_user_remote_storage.rs
> +    msg: &str,
-> `cla:&CoLink, clb:&CoLink`

2023-01-30 10:48 UTC, stneng commented on tests/test_user_remote_storage.rs
> +    let user_id_b = decode_jwt_without_validation(jwt_b).unwrap().user_id;
-> `let user_id_a=cla.get_user_id()?;`

2023-02-01 13:29 UTC, camelop requested changes
Generally looks good! Thanks for the effort!
A few questions (in addition to the detailed comments below):
1. PR name: it seems that we also have included other tests?
2. In previous rounds, examples are less seriously reviewed than core code, so although I understand you borrow some code from examples, it's still useful to further revise them as testing is more important.
3. In general, it might be beneficial if we include more assertions in these tests (major difference between examples and tests)

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +use colink::{
filename: actually, although we use a prefix `user_` to distinguish examples, I'm not sure if we still need to do that for tests. Considering it is fair to call this a test for lock, maybe we should remove the prefix? (same for the func name, same for the other file)

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +    user_lock_fn(&cl).await?;
a function that only occurs once, consider inlining it?

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +                        // println!("{}", num);
consider removing debugging prints, or use logging instead

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +    // println!("{:?}", ans);
same here

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +use colink::{
Also, it seems that this is a test using a counter, maybe `test_counter_with_lock` is more appropriate?

2023-02-01 13:29 UTC, camelop commented on tests/test_user_lock.rs
> +                    .enable_all()
oh, just occur to me that shall we also assert that we have more than one thread running the test for this? (if not, we shall skip the test as it's not informative?)

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +use colink::{
filename: same here

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +
usually we use empty lines for separation for longer code blocks

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +    cla: &CoLink,
`cl_a` might be better?

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +    // println!("{}", String::from_utf8_lossy(&data));
remove comments? or uncommenting them?

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +    // println!("{}", String::from_utf8_lossy(&data));
same here

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +    // println!("{}", String::from_utf8_lossy(&data));
Actually, I think we should make assertions in a test, rather than manually checking the printing results?

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +        // println!("{}", String::from_utf8_lossy(&*message.payload));
same

2023-02-01 13:29 UTC, camelop commented on tests/test_user_remote_storage.rs
> +    user_remote_storage_fn(&cla, &clb, test_msg).await?;
similarly, consider inlining the function

2023-02-01 14:19 UTC, camelop approved these changes
Looks good!

2023-02-01 14:32 UTC, merged